GET http://localhost:4000/progress?username=third1mpact&offset=500

###

GET http://localhost:4000/progress?username=robk34c

###

GET http://localhost:4000/users?username=rOBk34c

###

GET https://serene-temple-88689.herokuapp.com/progress?username=timsilog

###

GET http://localhost:4000/songs?songname=Silver%20and%20Gold%20dance

###

# POST https://serene-temple-88689.herokuapp.com/updateProgress
POST http://localhost:4000/updateProgress
Content-Type: application/json

{
  "songName": "test",
  "songArtist": "test",
  "anime": "test",
  "songLink": "test",
  "songType": "test",
  "username": "test",
  "guess": "test",
  "isCorrect": false
}

###

POST http://localhost:4000/addappt
Content-Type: application/json

{
  "doctorId": "d2",
  "date": "2020-05-07T03:40:00",
  "kind": "Follow-up"
}

###

GET http://localhost:4000/appointments?doctorId=d2&date=2020-05-07T03:30

###

DELETE http://localhost:4000/delappt
Content-Type: application/json

{
  "doctorId": "d3",
  "date": "2020-05-12T03:30:00",
  "apptId": "1"
}

###

PATCH http://localhost:4000/updateappt
Content-Type: application/json

{
  "doctorId": "d2",
  "date": "2020-05-07T03:30:00",
  "apptId": "3",
  "update": {
    "kind": "New Patient",
    "time": "2020-5-12T04:00:00"
  }
}